Modify ModelDecorator#initialize so that model default is nil
-----FAILING TEST-----

1) ModelDecorator#decorate adds a uuid to a model
   Failure/Error: uuid               = ModelDecorator.new.decorate(model_without_uuid)
   NoMethodError:
     undefined method `decorate' for #<ModelDecorator:0x007fc27b34b3f0 @model=nil>